# Generated by Django 3.2.6 on 2021-09-02 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customerorder', to='ordering.customer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='item',
            field=models.ManyToManyField(related_name='itemorder', to='ordering.Item'),
        ),
    ]
