# Generated by Django 2.2.12 on 2021-09-05 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0005_auto_20210905_0654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='ordering.Customer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='item',
            field=models.ManyToManyField(related_name='order', to='ordering.Item'),
        ),
    ]
