# Generated by Django 2.2.12 on 2021-09-05 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0006_auto_20210905_0811'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordering.Item')),
            ],
            options={
                'db_table': 'ordering_order_item',
            },
        ),
        migrations.AlterField(
            model_name='order',
            name='item',
            field=models.ManyToManyField(related_name='order', through='ordering.OrderItems', to='ordering.Item'),
        ),
        migrations.AddField(
            model_name='orderitems',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordering.Order'),
        ),
    ]
